version: "3"
services:
  client:
    container_name: dientsys-client
    build: ./client
    ports:
      - "3000:3000"
    command: pnpm dev
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    stdin_open: true
    tty: true
